// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // Archtype
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Archtype
    {
        public int ArchtypeId { get; set; } // ArchtypeId (Primary key)
        public int? ArchtypeRankId { get; set; } // ArchtypeRankId
        public string ArchtypeName { get; set; } // ArchtypeName (length: 24)
        public string ArchtypeShortDescription { get; set; } // ArchtypeShortDescription (length: 50)
        public string ArchtypeDescription { get; set; } // ArchtypeDescription (length: 150)
        public int? ArchtypeUnlockId { get; set; } // ArchtypeUnlockId

        // Reverse navigation

        /// <summary>
        /// Parent (One-to-One) Archtype pointed by [ArchtypeBonus].[ArchtypeId] (FK_RaceBonus_Race)
        /// </summary>
        public virtual ArchtypeBonu ArchtypeBonu { get; set; } // ArchtypeBonus.FK_RaceBonus_Race
        /// <summary>
        /// Child Characters where [Character].[CharacterPrimaryArchtypeId] point to this entity (FK_Character_PrimaryArchtype)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Character> Characters_CharacterPrimaryArchtypeId { get; set; } // Character.FK_Character_PrimaryArchtype
        /// <summary>
        /// Child Characters where [Character].[CharacterSecondaryArchtypeId] point to this entity (FK_Character_SecondaryArchtype)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Character> Characters_CharacterSecondaryArchtypeId { get; set; } // Character.FK_Character_SecondaryArchtype
        /// <summary>
        /// Child Characters where [Character].[CharacterTertiaryArchtypeId] point to this entity (FK_Character_TertiaryArchtype)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Character> Characters_CharacterTertiaryArchtypeId { get; set; } // Character.FK_Character_TertiaryArchtype
        /// <summary>
        /// Child Spells (Many-to-Many) mapped by table [ArchtypeSpellList]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Spell> Spells { get; set; } // Many to many mapping

        // Foreign keys

        /// <summary>
        /// Parent Rank pointed by [Archtype].([ArchtypeRankId]) (FK_Archtype_Rank)
        /// </summary>
        public virtual Rank Rank { get; set; } // FK_Archtype_Rank

        /// <summary>
        /// Parent Unlock pointed by [Archtype].([ArchtypeUnlockId]) (FK_Archtype_Unlock)
        /// </summary>
        public virtual Unlock Unlock { get; set; } // FK_Archtype_Unlock

        public Archtype()
        {
            Characters_CharacterPrimaryArchtypeId = new System.Collections.Generic.List<Character>();
            Characters_CharacterSecondaryArchtypeId = new System.Collections.Generic.List<Character>();
            Characters_CharacterTertiaryArchtypeId = new System.Collections.Generic.List<Character>();
            Spells = new System.Collections.Generic.List<Spell>();
        }
    }

}
// </auto-generated>
