// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // ArchtypeDetail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class ArchtypeDetail
    {
        public int ArchtypeId { get; set; } // ArchtypeId (Primary key)
        public string ArchtypeShortDescription { get; set; } // ArchtypeShortDescription (length: 50)
        public string ArchtypeDescription { get; set; } // ArchtypeDescription (length: 100)

        // Foreign keys

        /// <summary>
        /// Parent Archtype pointed by [ArchtypeDetail].([ArchtypeId]) (FK_ArchtypeDetail_ArchType)
        /// </summary>
        public virtual Archtype Archtype { get; set; } // FK_ArchtypeDetail_ArchType
    }

}
// </auto-generated>
