// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // ArchtypeSpellList
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class ArchtypeSpellListConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ArchtypeSpellList>
    {
        public ArchtypeSpellListConfiguration()
            : this("dbo")
        {
        }

        public ArchtypeSpellListConfiguration(string schema)
        {
            ToTable("ArchtypeSpellList", schema);
            HasKey(x => new { x.ArchtypeId, x.SpellId });

            Property(x => x.ArchtypeId).HasColumnName(@"ArchtypeId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SpellId).HasColumnName(@"SpellId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Archtype).WithMany(b => b.ArchtypeSpellLists).HasForeignKey(c => c.ArchtypeId).WillCascadeOnDelete(false); // FK_ArchtypeSpellList_Archtype
            HasRequired(a => a.Spell).WithMany(b => b.ArchtypeSpellLists).HasForeignKey(c => c.ArchtypeId).WillCascadeOnDelete(false); // FK_ArchtypeSpellList_Spell
        }
    }

}
// </auto-generated>
