// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // ArchtypeBonus
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class ArchtypeBonuConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ArchtypeBonu>
    {
        public ArchtypeBonuConfiguration()
            : this("dbo")
        {
        }

        public ArchtypeBonuConfiguration(string schema)
        {
            ToTable("ArchtypeBonus", schema);
            HasKey(x => x.ArchtypeId);

            Property(x => x.ArchtypeId).HasColumnName(@"ArchtypeId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.BonusHealth).HasColumnName(@"BonusHealth").HasColumnType("int").IsRequired();
            Property(x => x.BonusStamina).HasColumnName(@"BonusStamina").HasColumnType("int").IsRequired();
            Property(x => x.BonusConcentration).HasColumnName(@"BonusConcentration").HasColumnType("int").IsRequired();
            Property(x => x.BonusStrength).HasColumnName(@"BonusStrength").HasColumnType("int").IsRequired();
            Property(x => x.BonusAgility).HasColumnName(@"BonusAgility").HasColumnType("int").IsRequired();
            Property(x => x.BonusIntellect).HasColumnName(@"BonusIntellect").HasColumnType("int").IsRequired();
            Property(x => x.BonusBlock).HasColumnName(@"BonusBlock").HasColumnType("int").IsRequired();
            Property(x => x.BonusDodge).HasColumnName(@"BonusDodge").HasColumnType("int").IsRequired();
            Property(x => x.BonusResist).HasColumnName(@"BonusResist").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Archtype).WithOptional(b => b.ArchtypeBonu).WillCascadeOnDelete(false); // FK_RaceBonus_Race
        }
    }

}
// </auto-generated>
