// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // ArchtypeBonus
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class ArchtypeBonu
    {
        public int ArchtypeId { get; set; } // ArchtypeId (Primary key)
        public int BonusHealth { get; set; } // BonusHealth
        public int BonusStamina { get; set; } // BonusStamina
        public int BonusStrength { get; set; } // BonusStrength
        public int BonusAgility { get; set; } // BonusAgility
        public int BonusIntellect { get; set; } // BonusIntellect
        public int BonusFortitude { get; set; } // BonusFortitude
        public int BonusEndurance { get; set; } // BonusEndurance
        public int BonusConstitution { get; set; } // BonusConstitution

        // Foreign keys

        /// <summary>
        /// Parent Archtype pointed by [ArchtypeBonus].([ArchtypeId]) (FK_ArchtypeBonus_Archtype)
        /// </summary>
        public virtual Archtype Archtype { get; set; } // FK_ArchtypeBonus_Archtype
    }

}
// </auto-generated>
