// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // ArchtypeSpellList
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class ArchtypeSpellList
    {
        public int ArchtypeId { get; set; } // ArchtypeId (Primary key)
        public int SpellId { get; set; } // SpellId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Archtype pointed by [ArchtypeSpellList].([ArchtypeId]) (FK_ArchtypeSpellList_Archtype)
        /// </summary>
        public virtual Archtype Archtype { get; set; } // FK_ArchtypeSpellList_Archtype

        /// <summary>
        /// Parent Spell pointed by [ArchtypeSpellList].([ArchtypeId]) (FK_ArchtypeSpellList_Spell)
        /// </summary>
        public virtual Spell Spell { get; set; } // FK_ArchtypeSpellList_Spell
    }

}
// </auto-generated>
