// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // Archtype
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Archtype
    {
        public int ArchtypeId { get; set; } // ArchtypeId (Primary key)
        public string ArchtypeName { get; set; } // ArchtypeName (length: 50)

        // Reverse navigation

        /// <summary>
        /// Parent (One-to-One) Archtype pointed by [ArchtypeBonus].[ArchtypeId] (FK_ArchtypeBonus_Archtype)
        /// </summary>
        public virtual ArchtypeBonu ArchtypeBonu { get; set; } // ArchtypeBonus.FK_ArchtypeBonus_Archtype
        /// <summary>
        /// Parent (One-to-One) Archtype pointed by [ArchtypeDetail].[ArchtypeId] (FK_ArchtypeDetail_ArchType)
        /// </summary>
        public virtual ArchtypeDetail ArchtypeDetail { get; set; } // ArchtypeDetail.FK_ArchtypeDetail_ArchType
        /// <summary>
        /// Child ArchtypeSpellLists where [ArchtypeSpellList].[ArchtypeId] point to this entity (FK_ArchtypeSpellList_Archtype)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ArchtypeSpellList> ArchtypeSpellLists { get; set; } // ArchtypeSpellList.FK_ArchtypeSpellList_Archtype
        /// <summary>
        /// Child Characters where [Character].[CharacterPrimaryArchtypeId] point to this entity (FK_Character_Primary_Archtype)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Character> Characters_CharacterPrimaryArchtypeId { get; set; } // Character.FK_Character_Primary_Archtype
        /// <summary>
        /// Child Characters where [Character].[CharacterSecondaryArchtypeId] point to this entity (FK_Character_Secondary_Archtype)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Character> Characters_CharacterSecondaryArchtypeId { get; set; } // Character.FK_Character_Secondary_Archtype

        public Archtype()
        {
            ArchtypeSpellLists = new System.Collections.Generic.List<ArchtypeSpellList>();
            Characters_CharacterPrimaryArchtypeId = new System.Collections.Generic.List<Character>();
            Characters_CharacterSecondaryArchtypeId = new System.Collections.Generic.List<Character>();
        }
    }

}
// </auto-generated>
