// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // ArchtypeDetail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class ArchtypeDetail
    {
        public int ArchtypeId { get; set; } // ArchtypeId (Primary key)
        public string ArchtypeDescription { get; set; } // ArchtypeDescription (length: 100)

        // Reverse navigation

        /// <summary>
        /// Parent (One-to-One) ArchtypeDetail pointed by [Archtype].[ArchtypeId] (FK_Archtype_ArchtypeDetail)
        /// </summary>
        public virtual Archtype Archtype { get; set; } // Archtype.FK_Archtype_ArchtypeDetail
    }

}
// </auto-generated>
