// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // CharacterStatus
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class CharacterStatu
    {
        public int CharacterId { get; set; } // CharacterId (Primary key)
        public int? CharacterPrimaryResourceId { get; set; } // CharacterPrimaryResourceId
        public int? CharacterSecondaryResourceId { get; set; } // CharacterSecondaryResourceId

        // Foreign keys

        /// <summary>
        /// Parent Character pointed by [CharacterStatus].([CharacterId]) (FK_CharacterStatus_Character)
        /// </summary>
        public virtual Character Character { get; set; } // FK_CharacterStatus_Character

        /// <summary>
        /// Parent Resource pointed by [CharacterStatus].([CharacterPrimaryResourceId]) (FK_CharacterStatus_Primary_Resource)
        /// </summary>
        public virtual Resource CharacterPrimaryResource { get; set; } // FK_CharacterStatus_Primary_Resource

        /// <summary>
        /// Parent Resource pointed by [CharacterStatus].([CharacterSecondaryResourceId]) (FK_CharacterStatus_Secondary_Resource)
        /// </summary>
        public virtual Resource CharacterSecondaryResource { get; set; } // FK_CharacterStatus_Secondary_Resource
    }

}
// </auto-generated>
