// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // CharacterBonus
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class CharacterBonu
    {
        public int CharacterId { get; set; } // CharacterId (Primary key)
        public int CharacterBaseHealth { get; set; } // CharacterBaseHealth
        public int CharacterCurrentHealth { get; set; } // CharacterCurrentHealth
        public int CharacterBaseStamina { get; set; } // CharacterBaseStamina
        public int CharacterCurrentStamina { get; set; } // CharacterCurrentStamina
        public int CharacterBaseStrength { get; set; } // CharacterBaseStrength
        public int CharacterBaseAgility { get; set; } // CharacterBaseAgility
        public int CharacterBaseIntellect { get; set; } // CharacterBaseIntellect
        public int CharacterBaseBlock { get; set; } // CharacterBaseBlock
        public int CharacterBaseDodge { get; set; } // CharacterBaseDodge
        public int CharacterBaseResist { get; set; } // CharacterBaseResist

        // Foreign keys

        /// <summary>
        /// Parent Character pointed by [CharacterBonus].([CharacterId]) (FK_CharacterStatus_Character)
        /// </summary>
        public virtual Character Character { get; set; } // FK_CharacterStatus_Character
    }

}
// </auto-generated>
