// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // CharacterSpell
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class CharacterSpellConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CharacterSpell>
    {
        public CharacterSpellConfiguration()
            : this("dbo")
        {
        }

        public CharacterSpellConfiguration(string schema)
        {
            ToTable("CharacterSpell", schema);
            HasKey(x => x.CharacterId);

            Property(x => x.CharacterId).HasColumnName(@"CharacterId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.BaseSpellId).HasColumnName(@"BaseSpellId").HasColumnType("int").IsOptional();
            Property(x => x.PrimarySpellId).HasColumnName(@"PrimarySpellId").HasColumnType("int").IsOptional();
            Property(x => x.SecondarySpellId).HasColumnName(@"SecondarySpellId").HasColumnType("int").IsOptional();
            Property(x => x.TertiarySpellId).HasColumnName(@"TertiarySpellId").HasColumnType("int").IsOptional();

            // Foreign keys
            HasRequired(a => a.Character).WithOptional(b => b.CharacterSpell).WillCascadeOnDelete(false); // FK_CharacterSpell_Character
        }
    }

}
// </auto-generated>
