// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // CharacterStatus
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class CharacterStatuConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CharacterStatu>
    {
        public CharacterStatuConfiguration()
            : this("dbo")
        {
        }

        public CharacterStatuConfiguration(string schema)
        {
            ToTable("CharacterStatus", schema);
            HasKey(x => x.CharacterId);

            Property(x => x.CharacterId).HasColumnName(@"CharacterId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CharacterBaseHealth).HasColumnName(@"CharacterBaseHealth").HasColumnType("int").IsRequired();
            Property(x => x.CharacterCurrentHealth).HasColumnName(@"CharacterCurrentHealth").HasColumnType("int").IsRequired();
            Property(x => x.CharacterBaseStamina).HasColumnName(@"CharacterBaseStamina").HasColumnType("int").IsRequired();
            Property(x => x.CharacterCurrentStamina).HasColumnName(@"CharacterCurrentStamina").HasColumnType("int").IsRequired();
            Property(x => x.CharacterBaseStrength).HasColumnName(@"CharacterBaseStrength").HasColumnType("int").IsRequired();
            Property(x => x.CharacterBaseAgility).HasColumnName(@"CharacterBaseAgility").HasColumnType("int").IsRequired();
            Property(x => x.CharacterBaseIntellect).HasColumnName(@"CharacterBaseIntellect").HasColumnType("int").IsRequired();
            Property(x => x.CharacterBaseFortitude).HasColumnName(@"CharacterBaseFortitude").HasColumnType("int").IsRequired();
            Property(x => x.CharacterBaseEndurance).HasColumnName(@"CharacterBaseEndurance").HasColumnType("int").IsRequired();
            Property(x => x.CharacterBaseConstitution).HasColumnName(@"CharacterBaseConstitution").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Character).WithOptional(b => b.CharacterStatu).WillCascadeOnDelete(false); // FK_CharacterStatus_Character
        }
    }

}
// </auto-generated>
