// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{


    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class GnsDbContext : System.Data.Entity.DbContext, IGnsDbContext
    {
        public System.Data.Entity.DbSet<Archtype> Archtypes { get; set; } // Archtype
        public System.Data.Entity.DbSet<ArchtypeBonu> ArchtypeBonus { get; set; } // ArchtypeBonus
        public System.Data.Entity.DbSet<ArchtypeDetail> ArchtypeDetails { get; set; } // ArchtypeDetail
        public System.Data.Entity.DbSet<ArchtypeSpellList> ArchtypeSpellLists { get; set; } // ArchtypeSpellList
        public System.Data.Entity.DbSet<Character> Characters { get; set; } // Character
        public System.Data.Entity.DbSet<CharacterStatu> CharacterStatus { get; set; } // CharacterStatus
        public System.Data.Entity.DbSet<Player> Players { get; set; } // Player
        public System.Data.Entity.DbSet<PlayerDeck> PlayerDecks { get; set; } // PlayerDeck
        public System.Data.Entity.DbSet<Race> Races { get; set; } // Race
        public System.Data.Entity.DbSet<RaceBonu> RaceBonus { get; set; } // RaceBonus
        public System.Data.Entity.DbSet<RaceDetail> RaceDetails { get; set; } // RaceDetail
        public System.Data.Entity.DbSet<Spell> Spells { get; set; } // Spell
        public System.Data.Entity.DbSet<SpellDetail> SpellDetails { get; set; } // SpellDetail

        static GnsDbContext()
        {
            System.Data.Entity.Database.SetInitializer<GnsDbContext>(null);
        }

        public GnsDbContext()
            : base("Name=GnsConnectionString")
        {
        }

        public GnsDbContext(string connectionString)
            : base(connectionString)
        {
        }

        public GnsDbContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
        }

        public GnsDbContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
        }

        public GnsDbContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new ArchtypeConfiguration());
            modelBuilder.Configurations.Add(new ArchtypeBonuConfiguration());
            modelBuilder.Configurations.Add(new ArchtypeDetailConfiguration());
            modelBuilder.Configurations.Add(new ArchtypeSpellListConfiguration());
            modelBuilder.Configurations.Add(new CharacterConfiguration());
            modelBuilder.Configurations.Add(new CharacterStatuConfiguration());
            modelBuilder.Configurations.Add(new PlayerConfiguration());
            modelBuilder.Configurations.Add(new PlayerDeckConfiguration());
            modelBuilder.Configurations.Add(new RaceConfiguration());
            modelBuilder.Configurations.Add(new RaceBonuConfiguration());
            modelBuilder.Configurations.Add(new RaceDetailConfiguration());
            modelBuilder.Configurations.Add(new SpellConfiguration());
            modelBuilder.Configurations.Add(new SpellDetailConfiguration());
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new ArchtypeConfiguration(schema));
            modelBuilder.Configurations.Add(new ArchtypeBonuConfiguration(schema));
            modelBuilder.Configurations.Add(new ArchtypeDetailConfiguration(schema));
            modelBuilder.Configurations.Add(new ArchtypeSpellListConfiguration(schema));
            modelBuilder.Configurations.Add(new CharacterConfiguration(schema));
            modelBuilder.Configurations.Add(new CharacterStatuConfiguration(schema));
            modelBuilder.Configurations.Add(new PlayerConfiguration(schema));
            modelBuilder.Configurations.Add(new PlayerDeckConfiguration(schema));
            modelBuilder.Configurations.Add(new RaceConfiguration(schema));
            modelBuilder.Configurations.Add(new RaceBonuConfiguration(schema));
            modelBuilder.Configurations.Add(new RaceDetailConfiguration(schema));
            modelBuilder.Configurations.Add(new SpellConfiguration(schema));
            modelBuilder.Configurations.Add(new SpellDetailConfiguration(schema));
            return modelBuilder;
        }
    }
}
// </auto-generated>
