// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    public interface IGnsDbContext : System.IDisposable
    {
        System.Data.Entity.DbSet<Archtype> Archtypes { get; set; } // Archtype
        System.Data.Entity.DbSet<ArchtypeBonu> ArchtypeBonus { get; set; } // ArchtypeBonus
        System.Data.Entity.DbSet<ArchtypeDetail> ArchtypeDetails { get; set; } // ArchtypeDetail
        System.Data.Entity.DbSet<ArchtypeSpellList> ArchtypeSpellLists { get; set; } // ArchtypeSpellList
        System.Data.Entity.DbSet<Character> Characters { get; set; } // Character
        System.Data.Entity.DbSet<CharacterStatu> CharacterStatus { get; set; } // CharacterStatus
        System.Data.Entity.DbSet<Player> Players { get; set; } // Player
        System.Data.Entity.DbSet<PlayerDeck> PlayerDecks { get; set; } // PlayerDeck
        System.Data.Entity.DbSet<Race> Races { get; set; } // Race
        System.Data.Entity.DbSet<RaceBonu> RaceBonus { get; set; } // RaceBonus
        System.Data.Entity.DbSet<RaceDetail> RaceDetails { get; set; } // RaceDetail
        System.Data.Entity.DbSet<Spell> Spells { get; set; } // Spell
        System.Data.Entity.DbSet<SpellDetail> SpellDetails { get; set; } // SpellDetail

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
