// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    public interface IGnsDbContext : System.IDisposable
    {
        System.Data.Entity.DbSet<Archtype> Archtypes { get; set; } // Archtype
        System.Data.Entity.DbSet<ArchtypeBonu> ArchtypeBonus { get; set; } // ArchtypeBonus
        System.Data.Entity.DbSet<Character> Characters { get; set; } // Character
        System.Data.Entity.DbSet<CharacterBonu> CharacterBonus { get; set; } // CharacterBonus
        System.Data.Entity.DbSet<CharacterSpell> CharacterSpells { get; set; } // CharacterSpell
        System.Data.Entity.DbSet<Player> Players { get; set; } // Player
        System.Data.Entity.DbSet<Rank> Ranks { get; set; } // Rank
        System.Data.Entity.DbSet<Rarity> Rarities { get; set; } // Rarity
        System.Data.Entity.DbSet<Spell> Spells { get; set; } // Spell
        System.Data.Entity.DbSet<SpellDetail> SpellDetails { get; set; } // SpellDetail
        System.Data.Entity.DbSet<Unlock> Unlocks { get; set; } // Unlock

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
