// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // PlayerDetail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class PlayerDetail
    {
        public int PlayerId { get; set; } // PlayerId (Primary key)
        public int? ActiveCharacterId { get; set; } // ActiveCharacterId

        // Foreign keys

        /// <summary>
        /// Parent Character pointed by [PlayerDetail].([ActiveCharacterId]) (FK_PlayerDetail_Character)
        /// </summary>
        public virtual Character Character { get; set; } // FK_PlayerDetail_Character

        /// <summary>
        /// Parent Player pointed by [PlayerDetail].([PlayerId]) (FK_PlayerDetail_Player)
        /// </summary>
        public virtual Player Player { get; set; } // FK_PlayerDetail_Player
    }

}
// </auto-generated>
