// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // PlayerDetail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class PlayerDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PlayerDetail>
    {
        public PlayerDetailConfiguration()
            : this("dbo")
        {
        }

        public PlayerDetailConfiguration(string schema)
        {
            ToTable("PlayerDetail", schema);
            HasKey(x => x.PlayerId);

            Property(x => x.PlayerId).HasColumnName(@"PlayerId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ActiveCharacterId).HasColumnName(@"ActiveCharacterId").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.Character).WithMany(b => b.PlayerDetails).HasForeignKey(c => c.ActiveCharacterId).WillCascadeOnDelete(false); // FK_PlayerDetail_Character
            HasRequired(a => a.Player).WithOptional(b => b.PlayerDetail).WillCascadeOnDelete(false); // FK_PlayerDetail_Player
        }
    }

}
// </auto-generated>
