// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // PlayerDeck
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class PlayerDeck
    {
        public int PlayerId { get; set; } // PlayerId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Player pointed by [PlayerDeck].([PlayerId]) (FK_PlayerDeck_Player)
        /// </summary>
        public virtual Player Player { get; set; } // FK_PlayerDeck_Player
    }

}
// </auto-generated>
