// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // Race
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class RaceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Race>
    {
        public RaceConfiguration()
            : this("dbo")
        {
        }

        public RaceConfiguration(string schema)
        {
            ToTable("Race", schema);
            HasKey(x => x.RaceId);

            Property(x => x.RaceId).HasColumnName(@"RaceId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.RaceName).HasColumnName(@"RaceName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            HasMany(t => t.Spells).WithMany(t => t.Races).Map(m =>
            {
                m.ToTable("RaceSpellList", "dbo");
                m.MapLeftKey("RaceId");
                m.MapRightKey("SpellId");
            });
        }
    }

}
// </auto-generated>
