// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // Race
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Race
    {
        public int RaceId { get; set; } // RaceId (Primary key)
        public string RaceName { get; set; } // RaceName (length: 50)

        // Reverse navigation

        /// <summary>
        /// Parent (One-to-One) Race pointed by [RaceBonus].[RaceId] (FK_RaceBonus_Race)
        /// </summary>
        public virtual RaceBonu RaceBonu { get; set; } // RaceBonus.FK_RaceBonus_Race
        /// <summary>
        /// Parent (One-to-One) Race pointed by [RaceDetail].[RaceId] (FK_RaceDetail_Race)
        /// </summary>
        public virtual RaceDetail RaceDetail { get; set; } // RaceDetail.FK_RaceDetail_Race
        /// <summary>
        /// Child Characters where [Character].[CharacterRaceId] point to this entity (FK_Character_Race)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Character> Characters { get; set; } // Character.FK_Character_Race
        /// <summary>
        /// Child Spells (Many-to-Many) mapped by table [RaceSpellList]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Spell> Spells { get; set; } // Many to many mapping

        public Race()
        {
            Characters = new System.Collections.Generic.List<Character>();
            Spells = new System.Collections.Generic.List<Spell>();
        }
    }

}
// </auto-generated>
