// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // RaceBonus
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class RaceBonuConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RaceBonu>
    {
        public RaceBonuConfiguration()
            : this("dbo")
        {
        }

        public RaceBonuConfiguration(string schema)
        {
            ToTable("RaceBonus", schema);
            HasKey(x => x.RaceId);

            Property(x => x.RaceId).HasColumnName(@"RaceId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.BonusHealth).HasColumnName(@"BonusHealth").HasColumnType("int").IsRequired();
            Property(x => x.BonusStamina).HasColumnName(@"BonusStamina").HasColumnType("int").IsRequired();
            Property(x => x.BonusStrength).HasColumnName(@"BonusStrength").HasColumnType("int").IsRequired();
            Property(x => x.BonusAgility).HasColumnName(@"BonusAgility").HasColumnType("int").IsRequired();
            Property(x => x.BonusIntellect).HasColumnName(@"BonusIntellect").HasColumnType("int").IsRequired();
            Property(x => x.BonusFortitude).HasColumnName(@"BonusFortitude").HasColumnType("int").IsRequired();
            Property(x => x.BonusEndurance).HasColumnName(@"BonusEndurance").HasColumnType("int").IsRequired();
            Property(x => x.BonusConstitution).HasColumnName(@"BonusConstitution").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Race).WithOptional(b => b.RaceBonu).WillCascadeOnDelete(false); // FK_RaceBonus_Race
        }
    }

}
// </auto-generated>
