// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // RaceDetail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class RaceDetail
    {
        public int RaceId { get; set; } // RaceId (Primary key)
        public string RaceDescription { get; set; } // RaceDescription (length: 100)

        // Foreign keys

        /// <summary>
        /// Parent Race pointed by [RaceDetail].([RaceId]) (FK_RaceDetail_Race)
        /// </summary>
        public virtual Race Race { get; set; } // FK_RaceDetail_Race
    }

}
// </auto-generated>
