// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // RaceDetail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class RaceDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RaceDetail>
    {
        public RaceDetailConfiguration()
            : this("dbo")
        {
        }

        public RaceDetailConfiguration(string schema)
        {
            ToTable("RaceDetail", schema);
            HasKey(x => x.RaceId);

            Property(x => x.RaceId).HasColumnName(@"RaceId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.RaceShortDescription).HasColumnName(@"RaceShortDescription").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.RaceDescription).HasColumnName(@"RaceDescription").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);

            // Foreign keys
            HasRequired(a => a.Race).WithOptional(b => b.RaceDetail).WillCascadeOnDelete(false); // FK_RaceDetail_Race
        }
    }

}
// </auto-generated>
