// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // Rank
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Rank
    {
        public int RankId { get; set; } // RankId (Primary key)
        public string RankName { get; set; } // RankName (length: 24)

        // Reverse navigation

        /// <summary>
        /// Child Archtypes where [Archtype].[ArchtypeRankId] point to this entity (FK_Archtype_Rank)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Archtype> Archtypes { get; set; } // Archtype.FK_Archtype_Rank

        public Rank()
        {
            Archtypes = new System.Collections.Generic.List<Archtype>();
        }
    }

}
// </auto-generated>
