// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // Rank
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class RankConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Rank>
    {
        public RankConfiguration()
            : this("dbo")
        {
        }

        public RankConfiguration(string schema)
        {
            ToTable("Rank", schema);
            HasKey(x => x.RankId);

            Property(x => x.RankId).HasColumnName(@"RankId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.RankName).HasColumnName(@"RankName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(24);
        }
    }

}
// </auto-generated>
