// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // Rarity
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Rarity
    {
        public int RarityId { get; set; } // RarityId (Primary key)
        public string RarityName { get; set; } // RarityName (length: 50)
        public string RarityShortDescription { get; set; } // RarityShortDescription (length: 50)
        public string RarityLongDescription { get; set; } // RarityLongDescription (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Unlocks where [Unlock].[UnlockRarityId] point to this entity (FK_Unlock_Rarity)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Unlock> Unlocks { get; set; } // Unlock.FK_Unlock_Rarity

        public Rarity()
        {
            Unlocks = new System.Collections.Generic.List<Unlock>();
        }
    }

}
// </auto-generated>
