// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // Resource
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Resource
    {
        public int ResourceId { get; set; } // ResourceId (Primary key)
        public string ResourceName { get; set; } // ResourceName (length: 24)

        // Reverse navigation

        /// <summary>
        /// Child CharacterStatus where [CharacterStatus].[CharacterPrimaryResourceId] point to this entity (FK_CharacterStatus_Primary_Resource)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CharacterStatu> CharacterStatus_CharacterPrimaryResourceId { get; set; } // CharacterStatus.FK_CharacterStatus_Primary_Resource
        /// <summary>
        /// Child CharacterStatus where [CharacterStatus].[CharacterSecondaryResourceId] point to this entity (FK_CharacterStatus_Secondary_Resource)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CharacterStatu> CharacterStatus_CharacterSecondaryResourceId { get; set; } // CharacterStatus.FK_CharacterStatus_Secondary_Resource
        /// <summary>
        /// Child Races (Many-to-Many) mapped by table [RaceResourceList]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Race> Races { get; set; } // Many to many mapping

        public Resource()
        {
            CharacterStatus_CharacterPrimaryResourceId = new System.Collections.Generic.List<CharacterStatu>();
            CharacterStatus_CharacterSecondaryResourceId = new System.Collections.Generic.List<CharacterStatu>();
            Races = new System.Collections.Generic.List<Race>();
        }
    }

}
// </auto-generated>
