// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // SpellDetail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class SpellDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SpellDetail>
    {
        public SpellDetailConfiguration()
            : this("dbo")
        {
        }

        public SpellDetailConfiguration(string schema)
        {
            ToTable("SpellDetail", schema);
            HasKey(x => x.SpellId);

            Property(x => x.SpellId).HasColumnName(@"SpellId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SpellShortDescription).HasColumnName(@"SpellShortDescription").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.SpellDescription).HasColumnName(@"SpellDescription").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.SpellDamage).HasColumnName(@"SpellDamage").HasColumnType("int").IsOptional();
            Property(x => x.SpellCost).HasColumnName(@"SpellCost").HasColumnType("int").IsOptional();
            Property(x => x.SpellCooldown).HasColumnName(@"SpellCooldown").HasColumnType("int").IsOptional();

            // Foreign keys
            HasRequired(a => a.Spell).WithOptional(b => b.SpellDetail).WillCascadeOnDelete(false); // FK_SpellDetail_Spell
        }
    }

}
// </auto-generated>
