// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // SpellDetail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class SpellDetail
    {
        public int SpellId { get; set; } // SpellId (Primary key)
        public string SpellShortDescription { get; set; } // SpellShortDescription (length: 50)
        public string SpellDescription { get; set; } // SpellDescription (length: 100)
        public int? SpellDamage { get; set; } // SpellDamage
        public int? SpellCost { get; set; } // SpellCost
        public int? SpellCooldown { get; set; } // SpellCooldown

        // Foreign keys

        /// <summary>
        /// Parent Spell pointed by [SpellDetail].([SpellId]) (FK_SpellDetail_Spell)
        /// </summary>
        public virtual Spell Spell { get; set; } // FK_SpellDetail_Spell
    }

}
// </auto-generated>
