// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // Unlock
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class UnlockConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Unlock>
    {
        public UnlockConfiguration()
            : this("dbo")
        {
        }

        public UnlockConfiguration(string schema)
        {
            ToTable("Unlock", schema);
            HasKey(x => x.UnlockId);

            Property(x => x.UnlockId).HasColumnName(@"UnlockId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.UnlockName).HasColumnName(@"UnlockName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(24);
            Property(x => x.UnlockShortDescription).HasColumnName(@"UnlockShortDescription").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.UnlockLongDescription).HasColumnName(@"UnlockLongDescription").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(150);
            Property(x => x.UnlockRarityId).HasColumnName(@"UnlockRarityId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Rarity).WithMany(b => b.Unlocks).HasForeignKey(c => c.UnlockRarityId).WillCascadeOnDelete(false); // FK_Unlock_Rarity
        }
    }

}
// </auto-generated>
