// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GnsEntities
{

    // Unlock
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Unlock
    {
        public int UnlockId { get; set; } // UnlockId (Primary key)
        public string UnlockName { get; set; } // UnlockName (length: 24)
        public string UnlockShortDescription { get; set; } // UnlockShortDescription (length: 50)
        public string UnlockLongDescription { get; set; } // UnlockLongDescription (length: 150)
        public int UnlockRarityId { get; set; } // UnlockRarityId

        // Reverse navigation

        /// <summary>
        /// Child Archtypes where [Archtype].[ArchtypeUnlockId] point to this entity (FK_Archtype_Unlock)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Archtype> Archtypes { get; set; } // Archtype.FK_Archtype_Unlock
        /// <summary>
        /// Child Characters (Many-to-Many) mapped by table [CharacterUnlockList]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Character> Characters { get; set; } // Many to many mapping

        // Foreign keys

        /// <summary>
        /// Parent Rarity pointed by [Unlock].([UnlockRarityId]) (FK_Unlock_Rarity)
        /// </summary>
        public virtual Rarity Rarity { get; set; } // FK_Unlock_Rarity

        public Unlock()
        {
            Archtypes = new System.Collections.Generic.List<Archtype>();
            Characters = new System.Collections.Generic.List<Character>();
        }
    }

}
// </auto-generated>
